src/Entity/Inventory.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Entity\Chambre;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\InventoryRepository;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: InventoryRepository::class)]
class Inventory
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['inventory', 'user2', 'chambre2'])]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups(['inventory', 'user2', 'chambre2'])]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255)]
    #[Groups(['inventory', 'user2', 'chambre2'])]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Groups(['inventory', 'user2', 'chambre2'])]
    private ?string $prenom = null;
    
    #[ORM\Column]
    #[Groups(['inventory', 'user'])]
    private ?int $n_chambre = null;
    
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups(['inventory'])]
    private ?\DateTimeInterface $date_entree = null;
    
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    #[Groups(['inventory'])]
    private ?\DateTimeInterface $date_sortie = null;
    
    #[ORM\Column(length: 255)]
    #[Groups(['inventory'])]
    private ?string $section = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['inventory'])]
    private ?int $nombre_heures = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['inventory'])]
    private ?float $couts = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $adresse_sortie = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $porte_e_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $sol_e_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $mur_e_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $plafond_e_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $sol_ch_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $mur_ch_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $plafond_ch_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $fenetre_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prises_ch_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $armoire_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $bureau_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $table_chevet_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $chaises_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $lit_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $matelas_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $oreiller_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prise_tele_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prise_info_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prise_tv_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $luminaire_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $sol_sb_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $mur_sb_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $plafond_sb_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prises_sb_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $vasque_lavabo_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $toilettes_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $miroir_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $abattan_toilettes_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $patere_en = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $pare_douche_en = null;
    
    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $porte_e_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $sol_e_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $mur_e_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $plafond_e_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $sol_ch_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $mur_ch_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $plafond_ch_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $fenetre_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prises_ch_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $armoire_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $bureau_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $table_chevet_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $chaises_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $lit_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $matelas_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $oreiller_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prise_tele_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prise_info_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prise_tv_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $luminaire_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $sol_sb_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $mur_sb_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $plafond_sb_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $prises_sb_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $vasque_lavabo_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $toilettes_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $miroir_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $abattan_toilettes_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $patere_so = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['inventory'])]
    private ?string $pare_douche_so = null;

    #[ORM\ManyToOne(inversedBy: 'inventories')]
    // #[Groups(['inventory'])]
    private ?User $auteur = null;

    #[ORM\ManyToOne(inversedBy: 'inventories')]
    private ?Chambre $chambre = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNChambre(): ?int
    {
        return $this->n_chambre;
    }

    public function setNChambre(int $n_chambre): static
    {
        $this->n_chambre = $n_chambre;

        return $this;
    }

    public function getDateEntree(): ?\DateTimeInterface
    {
        return $this->date_entree;
    }

    public function setDateEntree(\DateTimeInterface $date_entree): static
    {

src/Form/InventoryType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use App\Entity\Inventory;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InventoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('createdAt', null, [
                'widget' => 'single_text',
            ])
            ->add('nom')
            ->add('prenom')
            ->add('n_chambre')
            ->add('date_entree', null, [
                'widget' => 'single_text',
            ])
            ->add('date_sortie', null, [
                'widget' => 'single_text',
            ])
            ->add('section')
            ->add('nombre_heures')
            ->add('couts')
            ->add('adresse_sortie')
            ->add('porte_e_en')
            ->add('sol_e_en')
            ->add('mur_e_en')
            ->add('plafond_e_en')
            ->add('sol_ch_en')
            ->add('mur_ch_en')
            ->add('plafond_ch_en')
            ->add('fenetre_en')
            ->add('prises_ch_en')
            ->add('armoire_en')
            ->add('bureau_en')
            ->add('table_chevet_en')
            ->add('chaises_en')
            ->add('lit_en')
            ->add('matelas_en')
            ->add('oreiller_en')
            ->add('prise_tele_en')
            ->add('prise_info_en')
            ->add('prise_tv_en')
            ->add('luminaire_en')
            ->add('sol_sb_en')
            ->add('mur_sb_en')
            ->add('plafond_sb_en')
            ->add('prises_sb_en')
            ->add('vasque_lavabo_en')
            ->add('toilettes_en')
            ->add('miroir_en')
            ->add('abattan_toilettes_en')
            ->add('patere_en')
            ->add('pare_douche_en')
            ->add('porte_e_so')
            ->add('sol_e_so')
            ->add('mur_e_so')
            ->add('plafond_e_so')
            ->add('sol_ch_so')
            ->add('mur_ch_so')
            ->add('plafond_ch_so')
            ->add('fenetre_so')
            ->add('prises_ch_so')
            ->add('armoire_so')
            ->add('bureau_so')
            ->add('table_chevet_so')
            ->add('chaises_so')
            ->add('lit_so')
            ->add('matelas_so')
            ->add('oreiller_so')
            ->add('prise_tele_so')
            ->add('prise_info_so')
            ->add('prise_tv_so')
            ->add('luminaire_so')
            ->add('sol_sb_so')
            ->add('mur_sb_so')
            ->add('plafond_sb_so')
            ->add('prises_sb_so')
            ->add('vasque_lavabo_so')
            ->add('toilettes_so')
            ->add('miroir_so')
            ->add('abattan_toilettes_so')
            ->add('patere_so')
            ->add('pare_douche_so')
            ->add('auteur', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'id',
            ])
            ->add('chambre', EntityType::class, [
                'class' => Chambre::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Inventory::class,
        ]);
    }
}

src/Controller/InventoryController.php
<?php

namespace App\Controller;

use App\Entity\Inventory;
use App\Form\InventoryType;
use App\Repository\InventoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/inventory')]
class InventoryController extends AbstractController
{
    #[Route('/', name: 'app_inventory_index', methods: ['GET'])]
    public function index(InventoryRepository $inventoryRepository): Response
    {
        return $this->render('inventory/index.html.twig', [
            'inventories' => $inventoryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_inventory_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $inventory = new Inventory();
        $form = $this->createForm(InventoryType::class, $inventory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($inventory);
            $entityManager->flush();

            return $this->redirectToRoute('app_inventory_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('inventory/new.html.twig', [
            'inventory' => $inventory,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_inventory_show', methods: ['GET'])]
    public function show(Inventory $inventory): Response
    {
        return $this->render('inventory/show.html.twig', [
            'inventory' => $inventory,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_inventory_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Inventory $inventory, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(InventoryType::class, $inventory);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_inventory_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('inventory/edit.html.twig', [
            'inventory' => $inventory,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_inventory_delete', methods: ['POST'])]
    public function delete(Request $request, Inventory $inventory, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$inventory->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($inventory);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_inventory_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/inventory/_delete_form.html.twig
<form method="post" action="{{ path('app_inventory_delete', {'id': inventory.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ inventory.id) }}">
    <button class="btn">Delete</button>
</form>

templates/inventory/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/inventory/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Inventory{% endblock %}

{% block body %}
    <h1>Edit Inventory</h1>

    {{ include('inventory/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_inventory_index') }}">back to list</a>

    {{ include('inventory/_delete_form.html.twig') }}
{% endblock %}

templates/inventory/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inventory index{% endblock %}

{% block body %}
    <h1>Inventory index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>CreatedAt</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>N_chambre</th>
                <th>Date_entree</th>
                <th>Date_sortie</th>
                <th>Section</th>
                <th>Nombre_heures</th>
                <th>Couts</th>
                <th>Adresse_sortie</th>
                <th>Porte_e_en</th>
                <th>Sol_e_en</th>
                <th>Mur_e_en</th>
                <th>Plafond_e_en</th>
                <th>Sol_ch_en</th>
                <th>Mur_ch_en</th>
                <th>Plafond_ch_en</th>
                <th>Fenetre_en</th>
                <th>Prises_ch_en</th>
                <th>Armoire_en</th>
                <th>Bureau_en</th>
                <th>Table_chevet_en</th>
                <th>Chaises_en</th>
                <th>Lit_en</th>
                <th>Matelas_en</th>
                <th>Oreiller_en</th>
                <th>Prise_tele_en</th>
                <th>Prise_info_en</th>
                <th>Prise_tv_en</th>
                <th>Luminaire_en</th>
                <th>Sol_sb_en</th>
                <th>Mur_sb_en</th>
                <th>Plafond_sb_en</th>
                <th>Prises_sb_en</th>
                <th>Vasque_lavabo_en</th>
                <th>Toilettes_en</th>
                <th>Miroir_en</th>
                <th>Abattan_toilettes_en</th>
                <th>Patere_en</th>
                <th>Pare_douche_en</th>
                <th>Porte_e_so</th>
                <th>Sol_e_so</th>
                <th>Mur_e_so</th>
                <th>Plafond_e_so</th>
                <th>Sol_ch_so</th>
                <th>Mur_ch_so</th>
                <th>Plafond_ch_so</th>
                <th>Fenetre_so</th>
                <th>Prises_ch_so</th>
                <th>Armoire_so</th>
                <th>Bureau_so</th>
                <th>Table_chevet_so</th>
                <th>Chaises_so</th>
                <th>Lit_so</th>
                <th>Matelas_so</th>
                <th>Oreiller_so</th>
                <th>Prise_tele_so</th>
                <th>Prise_info_so</th>
                <th>Prise_tv_so</th>
                <th>Luminaire_so</th>
                <th>Sol_sb_so</th>
                <th>Mur_sb_so</th>
                <th>Plafond_sb_so</th>
                <th>Prises_sb_so</th>
                <th>Vasque_lavabo_so</th>
                <th>Toilettes_so</th>
                <th>Miroir_so</th>
                <th>Abattan_toilettes_so</th>
                <th>Patere_so</th>
                <th>Pare_douche_so</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for inventory in inventories %}
            <tr>
                <td>{{ inventory.id }}</td>
                <td>{{ inventory.createdAt ? inventory.createdAt|date('Y-m-d') : '' }}</td>
                <td>{{ inventory.nom }}</td>
                <td>{{ inventory.prenom }}</td>
                <td>{{ inventory.nChambre }}</td>
                <td>{{ inventory.dateEntree ? inventory.dateEntree|date('Y-m-d') : '' }}</td>
                <td>{{ inventory.dateSortie ? inventory.dateSortie|date('Y-m-d') : '' }}</td>
                <td>{{ inventory.section }}</td>
                <td>{{ inventory.nombreHeures }}</td>
                <td>{{ inventory.couts }}</td>
                <td>{{ inventory.adresseSortie }}</td>
                <td>{{ inventory.porteEEn }}</td>
                <td>{{ inventory.solEEn }}</td>
                <td>{{ inventory.murEEn }}</td>
                <td>{{ inventory.plafondEEn }}</td>
                <td>{{ inventory.solChEn }}</td>
                <td>{{ inventory.murChEn }}</td>
                <td>{{ inventory.plafondChEn }}</td>
                <td>{{ inventory.fenetreEn }}</td>
                <td>{{ inventory.prisesChEn }}</td>
                <td>{{ inventory.armoireEn }}</td>
                <td>{{ inventory.bureauEn }}</td>
                <td>{{ inventory.tableChevetEn }}</td>
                <td>{{ inventory.chaisesEn }}</td>
                <td>{{ inventory.litEn }}</td>
                <td>{{ inventory.matelasEn }}</td>
                <td>{{ inventory.oreillerEn }}</td>
                <td>{{ inventory.priseTeleEn }}</td>
                <td>{{ inventory.priseInfoEn }}</td>
                <td>{{ inventory.priseTvEn }}</td>
                <td>{{ inventory.luminaireEn }}</td>
                <td>{{ inventory.solSbEn }}</td>
                <td>{{ inventory.murSbEn }}</td>
                <td>{{ inventory.plafondSbEn }}</td>
                <td>{{ inventory.prisesSbEn }}</td>
                <td>{{ inventory.vasqueLavaboEn }}</td>
                <td>{{ inventory.toilettesEn }}</td>
                <td>{{ inventory.miroirEn }}</td>
                <td>{{ inventory.abattanToilettesEn }}</td>
                <td>{{ inventory.patereEn }}</td>
                <td>{{ inventory.pareDoucheEn }}</td>
                <td>{{ inventory.porteESo }}</td>
                <td>{{ inventory.solESo }}</td>
                <td>{{ inventory.murESo }}</td>
                <td>{{ inventory.plafondESo }}</td>
                <td>{{ inventory.solChSo }}</td>
                <td>{{ inventory.murChSo }}</td>
                <td>{{ inventory.plafondChSo }}</td>
                <td>{{ inventory.fenetreSo }}</td>
                <td>{{ inventory.prisesChSo }}</td>
                <td>{{ inventory.armoireSo }}</td>
                <td>{{ inventory.bureauSo }}</td>
                <td>{{ inventory.tableChevetSo }}</td>
                <td>{{ inventory.chaisesSo }}</td>
                <td>{{ inventory.litSo }}</td>
                <td>{{ inventory.matelasSo }}</td>
                <td>{{ inventory.oreillerSo }}</td>
                <td>{{ inventory.priseTeleSo }}</td>
                <td>{{ inventory.priseInfoSo }}</td>
                <td>{{ inventory.priseTvSo }}</td>
                <td>{{ inventory.luminaireSo }}</td>
                <td>{{ inventory.solSbSo }}</td>
                <td>{{ inventory.murSbSo }}</td>
                <td>{{ inventory.plafondSbSo }}</td>
                <td>{{ inventory.prisesSbSo }}</td>
                <td>{{ inventory.vasqueLavaboSo }}</td>
                <td>{{ inventory.toilettesSo }}</td>
                <td>{{ inventory.miroirSo }}</td>
                <td>{{ inventory.abattanToilettesSo }}</td>
                <td>{{ inventory.patereSo }}</td>
                <td>{{ inventory.pareDoucheSo }}</td>
                <td>
                    <a href="{{ path('app_inventory_show', {'id': inventory.id}) }}">show</a>
                    <a href="{{ path('app_inventory_edit', {'id': inventory.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="72">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_inventory_new') }}">Create new</a>
{% endblock %}

templates/inventory/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Inventory{% endblock %}

{% block body %}
    <h1>Create new Inventory</h1>

    {{ include('inventory/_form.html.twig') }}

    <a href="{{ path('app_inventory_index') }}">back to list</a>
{% endblock %}