src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Entity\Inventory;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ChambreRepository::class)]
class Chambre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['chambre', 'inventory'])]
    private ?int $id = null;

    #[ORM\Column]
    #[Groups(['chambre'])]
    private ?int $n_chambre = null;

    #[ORM\Column(length: 100)]
    #[Groups(['chambre', 'inventory'])]
    private ?string $nom_bat = null;

    #[ORM\Column]
    #[Groups(['chambre'])]
    private ?int $capacite = null;

    #[ORM\Column]
    #[Groups(['chambre'])]
    private ?int $capacite_lit = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['chambre'])]
    private ?string $handicap = null;

    #[ORM\Column(length: 255)]
    #[Groups(['chambre', 'inventory'])]
    private ?string $formation = null;

    #[ORM\Column(length: 100)]
    #[Groups(['chambre', 'inventory'])]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    #[Groups(['chambre', 'inventory'])]
    private ?string $prenom = null;

    #[ORM\Column]
    #[Groups(['chambre'])]
    private ?bool $isActive = null;

    /**
     * @var Collection<int, Inventory>
     */
    #[ORM\OneToMany(targetEntity: Inventory::class, mappedBy: 'chambre')]
    #[Groups(['chambre2'])]
    private Collection $inventories;

    #[ORM\Column(nullable: true)]
    private ?bool $isAbsent = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isPMR = null;

    
    // #[ORM\Column(nullable: true)]
    // private ?bool $isPMR = null;

    // #[ORM\Column(nullable: true)]
    // private ?bool $isAbsent = null;

    public function __construct()
    {
        $this->inventories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNChambre(): ?int
    {
        return $this->n_chambre;
    }

    public function setNChambre(int $n_chambre): static
    {
        $this->n_chambre = $n_chambre;

        return $this;
    }

    public function getNomBat(): ?string
    {
        return $this->nom_bat;
    }

    public function setNomBat(string $nom_bat): static
    {
        $this->nom_bat = $nom_bat;

        return $this;
    }

    public function getCapacite(): ?int
    {
        return $this->capacite;
    }

    public function setCapacite(int $capacite): static
    {
        $this->capacite = $capacite;

        return $this;
    }

    public function isCapaciteLit(): ?int
    {
        return $this->capacite_lit;
    }

    public function setCapaciteLit(int $capacite_lit): static
    {
        $this->capacite_lit = $capacite_lit;

        return $this;
    }

    public function getHandicap(): ?string
    {
        return $this->handicap;
    }

    public function setHandicap(?string $handicap): static
    {
        $this->handicap = $handicap;

        return $this;
    }

    public function getFormation(): ?string
    {
        return $this->formation;
    }

    public function setFormation(string $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->isActive;
    }

    public function setActive(bool $isActive): static
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection<int, Inventory>
     */
    public function getInventories(): Collection
    {
        return $this->inventories;
    }

    public function addInventory(Inventory $inventory): static
    {
        if (!$this->inventories->contains($inventory)) {
            $this->inventories->add($inventory);
            $inventory->setChambre($this);
        }

        return $this;
    }

    public function removeInventory(Inventory $inventory): static
    {
        if ($this->inventories->removeElement($inventory)) {
            // set the owning side to null (unless already changed)
            if ($inventory->getChambre() === $this) {
                $inventory->setChambre(null);
            }
        }

        return $this;
    }

    // public function isPMR(): ?bool
    // {
    //     return $this->isPMR;
    // }

    // public function setPMR(?bool $isPMR): static
    // {
    //     $this->isPMR = $isPMR;

    //     return $this;
    // }

    // public function isAbsent(): ?bool
    // {
    //     return $this->isAbsent;
    // }

    // public function setAbsent(?bool $isAbsent): static
    // {
    //     $this->isAbsent = $isAbsent;

    //     return $this;
    // }

    public function isAbsent(): ?bool
    {
        return $this->isAbsent;
    }

    public function setAbsent(?bool $isAbsent): static
    {
        $this->isAbsent = $isAbsent;

        return $this;
    }

    public function isPMR(): ?bool
    {
        return $this->isPMR;
    }

    public function setPMR(?bool $isPMR): static
    {
        $this->isPMR = $isPMR;

        return $this;
    }
}

src/Form/ChambreType.php
<?php

namespace App\Form;

use App\Entity\Chambre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChambreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('n_chambre')
            ->add('nom_bat')
            ->add('capacite')
            ->add('capacite_lit')
            ->add('handicap')
            ->add('formation')
            ->add('nom')
            ->add('prenom')
            ->add('isActive')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Chambre::class,
        ]);
    }
}

src/Controller/ChambreController.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Form\ChambreType;
use App\Repository\ChambreRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/chambre')]
class ChambreController extends AbstractController
{
    #[Route('/', name: 'app_chambre_index', methods: ['GET'])]
    public function index(ChambreRepository $chambreRepository): Response
    {
        return $this->render('chambre/index.html.twig', [
            'chambres' => $chambreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_chambre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $chambre = new Chambre();
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($chambre);
            $entityManager->flush();

            return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chambre/new.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chambre_show', methods: ['GET'])]
    public function show(Chambre $chambre): Response
    {
        return $this->render('chambre/show.html.twig', [
            'chambre' => $chambre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_chambre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ChambreType::class, $chambre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('chambre/edit.html.twig', [
            'chambre' => $chambre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_chambre_delete', methods: ['POST'])]
    public function delete(Request $request, Chambre $chambre, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$chambre->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($chambre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_chambre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/chambre/_delete_form.html.twig
<form method="post" action="{{ path('app_chambre_delete', {'id': chambre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chambre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/chambre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/chambre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Chambre{% endblock %}

{% block body %}
    <h1>Edit Chambre</h1>

    {{ include('chambre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_chambre_index') }}">back to list</a>

    {{ include('chambre/_delete_form.html.twig') }}
{% endblock %}

templates/chambre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chambre index{% endblock %}

{% block body %}
    <h1>Chambre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>N_chambre</th>
                <th>Nom_bat</th>
                <th>Capacite</th>
                <th>Capacite_lit</th>
                <th>Handicap</th>
                <th>Formation</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>IsActive</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for chambre in chambres %}
            <tr>
                <td>{{ chambre.id }}</td>
                <td>{{ chambre.nChambre }}</td>
                <td>{{ chambre.nomBat }}</td>
                <td>{{ chambre.capacite }}</td>
                <td>{{ chambre.capaciteLit ? 'Yes' : 'No' }}</td>
                <td>{{ chambre.handicap }}</td>
                <td>{{ chambre.formation }}</td>
                <td>{{ chambre.nom }}</td>
                <td>{{ chambre.prenom }}</td>
                <td>{{ chambre.isActive ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_chambre_show', {'id': chambre.id}) }}">show</a>
                    <a href="{{ path('app_chambre_edit', {'id': chambre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_chambre_new') }}">Create new</a>
{% endblock %}

templates/chambre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Chambre{% endblock %}

{% block body %}
    <h1>Create new Chambre</h1>

    {{ include('chambre/_form.html.twig') }}

    <a href="{{ path('app_chambre_index') }}">back to list</a>
{% endblock %}

templates/chambre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chambre{% endblock %}

{% block body %}
    <h1>Chambre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ chambre.id }}</td>
            </tr>
            <tr>
                <th>N_chambre</th>
                <td>{{ chambre.nChambre }}</td>
            </tr>
            <tr>
                <th>Nom_bat</th>
                <td>{{ chambre.nomBat }}</td>
            </tr>
            <tr>
                <th>Capacite</th>
                <td>{{ chambre.capacite }}</td>
            </tr>
            <tr>
                <th>Capacite_lit</th>
                <td>{{ chambre.capaciteLit ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Handicap</th>
                <td>{{ chambre.handicap }}</td>
            </tr>
            <tr>
                <th>Formation</th>
                <td>{{ chambre.formation }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ chambre.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ chambre.prenom }}</td>
            </tr>
            <tr>
                <th>IsActive</th>
                <td>{{ chambre.isActive ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_chambre_index') }}">back to list</a>

    <a href="{{ path('app_chambre_edit', {'id': chambre.id}) }}">edit</a>

    {{ include('chambre/_delete_form.html.twig') }}
{% endblock %}